Parameters:

  KeyName:
    Description: Enter a name of an existing key pair
    Type: String
    Default: myKP

Resources:
  firstpublicInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-00874d747dde814fa"
      KeyName: 
        Ref: "KeyName"
      NetworkInterfaces: 
        -  AssociatePublicIpAddress: "true"
           DeviceIndex: "0"
           GroupSet:
             -  Fn::ImportValue: "securityGroupOutput"
           SubnetId: 
             Fn::ImportValue: "FirstPublicSubnetOutput"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
            sudo apt update
            sudo apt upgrade -y
            curl -sfL https://get.docker.com -o docker.sh
            chmod +x docker.sh
            ./docker.sh
            sudo usermod -aG docker ubuntu

  secondpublicInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-00874d747dde814fa"
      KeyName: 
        Ref: "KeyName"
      NetworkInterfaces: 
        -  AssociatePublicIpAddress: "true"
           DeviceIndex: "0"
           GroupSet:
             -  Fn::ImportValue: "securityGroupOutput"
           SubnetId: 
             Fn::ImportValue: "SecondPublicSubnetOutput"
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe
            sudo apt update
            sudo apt upgrade -y
            curl -sfL https://get.docker.com -o docker.sh
            chmod +x docker.sh
            ./docker.sh
            sudo usermod -aG docker ubuntu
